### PR TITLE
fix webp for file conversion by magick

### PR DESCRIPTION
**Pull request by mvaranda**
This fix is working for my use-case:  files converted using magick tool.
However, I  believe that the original code was working for other EXIF formats.

Need regression test and, maybe, process EXIF according to its verion.

### CODE REVIEW

**Comment by ianare** [comment]
Thank you. I'm having some problems with travis on this repo, will take a better look when fixed.

**Comment by mvaranda** [comment]
For testing, the following link is the exif-samples/jpg/gps/DSCN0010.jpg converted to web using imageMagick 7.0.10:

https://drive.google.com/file/d/1lUqCjwB-O0NW5r2D7f7ougsV5RS5Ipxh/view?usp=sharing <https://drive.google.com/file/d/1lUqCjwB-O0NW5r2D7f7ougsV5RS5Ipxh/view?usp=sharing>

Cheers,
Marcelo

**Comment by ianare** [comment]
Sorry for the delay, finally got everything working. Can you rebase develop onto this branch? Thank you?

**Comment by mvaranda** [comment]
I am not able to test as my scripts were in my bz laptop and I move jobs. I may have somewhere a copy but will nee to dig.
Anyways... I do not see the line 50 in exifread/__init__.py having the proposed fix:

https://github.com/ianare/exif-py/pull/132/commits/e5d057807418d5b3a07611b0217bdbf36761a499

**Comment by ianare** [comment]
OK no worries I will take of it.

**Pull request merged**
