### PR TITLE
initial HEIC support.

### PR DESCRIPTION
**Pull request by samrushing**
Tested with Python 2.7.14 & 3.7.0 on my own iphone xs images and on a sample pack of random iOS device images found on the net.

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Related issue: #83

**Comment by ianare** [comment]
Thanks for the help! Looks good overall.

Please add your contribution and your name to the Changelog file.

Could you also add some test images in the sample images repo if possible?

https://github.com/ianare/exif-samples

**Comment by jaakla** [comment]
I tried with few images from iPhone X, it looks like it does not read GPS coordinates, all are None. Mac own preview shows location, so the coordinates must be present.

**Comment by chrstphrchvz** [comment]
> I tried with few images from iPhone X, it looks like it does not read GPS coordinates, all are None. Mac own preview shows location, so the coordinates must be present.

I believe this is a separate issue (not related to HEIC): #96

**Comment by jaakla** [comment]
> > I tried with few images from iPhone X, it looks like it does not read GPS coordinates, all are None. Mac own preview shows location, so the coordinates must be present.
> 
> I believe this is a separate issue (not related to HEIC): #96

Yes, this is this separate issue, after the update HEIC GPS works just fine.

**Pull request merged**
