### PR TITLE
Correcty process the Makernote of some Canon models

### PR DESCRIPTION
**Pull request by jcea**
Needed to correctly process Makernote of some Canon cameras. For instance Canon Powershot SX60.

After this pull request is accepted, I have two more about HDR tags.

### CODE REVIEW

**Comment by ianare** [comment]
Great, thank you!

If you have some test images for this, can you provide them? This way I will add to the test images repo.

**Comment by jcea** [comment]
ianare. Please copy them somewhere. I will delete them in the coming days.

https://blog.jcea.es/canon_hdr_NO.jpg
https://blog.jcea.es/canon_hdr_YES.jpg

https://blog.jcea.es/iphone_hdr_NO.jpg
https://blog.jcea.es/iphone_hdr_YES.jpg

The HDR images will be detected in two incoming pull requests.

**Comment by ianare** [comment]
Images added here: https://github.com/ianare/exif-samples/tree/master/jpg/hdr

So now these will be processed / tested on every Travis build.

You can delete from you server when you want. Thanks for all your help.

**Comment by jcea** [comment]
Good. Thanks. You will need to upgrade the tests when you accept the PR for Apple iOS HDR.

**Comment by jcea** [comment]
Could you possibly update the README to credit me? :)

**Comment by ianare** [comment]
I've added you to the changelog on exif-py and added a README in the hdr folder in exif-samples.

If you want me to use your real name rather than your username, please let me know (or submit a PR).

Thanks!

**Comment by ianare** [comment]
I had to revert the changes to the ifd processing, all other images I tested with had missing Makernotes.

**Comment by jcea** [comment]
Sorry for the regression. I only have a Canon PowerShot SX60 HS and I was expecting the Continuous Integration system to catch any issue.

Do you take care of this? I can try but not immediately.

**Comment by ianare** [comment]
For now I simply removed the code, but left the HDR tag definitions.
I will try to add better regression tests.

**Pull request merged**
